# Generated by Django 3.2.7 on 2021-10-22 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211022_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Наименование')),
                ('description', models.TextField(max_length=256, verbose_name='описание')),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category_news'),
        ),
        migrations.DeleteModel(
            name='Category_new',
        ),
    ]
