# Generated by Django 3.2.7 on 2021-10-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20211007_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='addon',
            new_name='addons',
        ),
    ]
