# Generated by Django 3.2.7 on 2021-10-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='gender',
            field=models.CharField(choices=[('x', 'male'), ('y', 'female')], default='', max_length=1, verbose_name='gender'),
        ),
    ]
