# Generated by Django 3.2.7 on 2021-10-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_addon_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('x', 'male'), ('y', 'female')], default='', max_length=1, verbose_name='gender'),
        ),
    ]
