# Generated by Django 3.2.7 on 2021-11-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20211022_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Наименование характеристики')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.AlterField(
            model_name='addon',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('kids', 'kids')], default='', max_length=6, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('kids', 'kids')], default='', max_length=6, verbose_name='gender'),
        ),
        migrations.CreateModel(
            name='AddonSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, verbose_name='Значение характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.addon')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.addonspecification')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
            },
        ),
        migrations.CreateModel(
            name='AddonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='images', verbose_name='изображение')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.addon')),
            ],
        ),
    ]
