# Generated by Django 3.2.7 on 2021-11-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20211107_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
    ]
