# Generated by Django 3.2.7 on 2021-11-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20211107_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('kids', 'kids')], default='', max_length=6, verbose_name='gender'),
        ),
    ]
