# Generated by Django 3.2.7 on 2021-11-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_category_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('kids', 'kids'), ('accessory', 'accessory')], default='', max_length=9, verbose_name='gender'),
        ),
    ]
