# Generated by Django 3.2.7 on 2021-11-09 20:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_category_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
