# Generated by Django 3.2.7 on 2021-11-09 20:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='color1',
        ),
        migrations.AddField(
            model_name='product',
            name='color2',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#FFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='product',
            name='color3',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#FFFFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='product',
            name='color4',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#FFFFFF', max_length=18),
        ),
    ]
