# Generated by Django 3.2.7 on 2021-11-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20211022_0639'),
        ('cart', '0003_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.addon')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
