# Generated by Django 3.2.7 on 2021-11-04 17:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartaddon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('phone', models.CharField(max_length=100, verbose_name='телефон')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='адресс')),
                ('status', models.CharField(choices=[('new', 'новый заказ'), ('in_progress', 'закакз в обработке'), ('is_ready', 'заказ готов'), ('completed', 'заказ выполнен')], default='new', max_length=100, verbose_name='статус заказа ')),
                ('buying_type', models.CharField(choices=[('self', 'самовывоз'), ('delivery', 'доставка')], default='self', max_length=100, verbose_name='тип заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='время создания заказа')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата получения заказа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='cart.customer', verbose_name='Покупатель')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_customer', to='cart.Order', verbose_name='Заказы'),
        ),
    ]
