# Generated by Django 3.2.7 on 2021-11-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20211104_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=models.Model, to='cart.customer'),
        ),
    ]
