# Generated by Django 3.2.7 on 2021-10-07 11:59

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211004_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.get_file_path, verbose_name='аватарка'),
        ),
    ]
